@ECHO OFF
SETLOCAL

@SET PROJECT_DIR=%~dp0
@IF "%PROJECT_DIR:~-1%" EQU "\" SET PROJECT_DIR=%PROJECT_DIR:~0,-1%

SET BUILD_DIR=%PROJECT_DIR%\build

if not exist "%BUILD_DIR%" MKDIR "%BUILD_DIR%"

pushd "%BUILD_DIR%"

set COMPILER=%VC64_CL%
IF "%COMPILER%" EQU "" SET COMPILER=cl

"%COMPILER%" /nologo /Zi "%PROJECT_DIR%\user_example.cpp"

popd

ENDLOCAL
EXIT /B 0
